### ISSUE TITLE
spade control

### ISSUE THREAD

**Issue by fatefly** [ashish-gehani/SPADE#124]
when spade control ,Unable to set up remote secure communication streams! java.net.ConnectException: Connection refused (Connection refused)

**Comment by hassaanirshad** [comment]
Sorry for the late reply. 

In general, that error occurs when SPADE control client is unable to talk to SPADE server. That can be because of multiple reasons:

1. SPADE is not running anymore because enough memory wasn't available. This can be checked by executing the command `./bin/spade status`.
2. There is an error in SPADE. This can be checked by looking at SPADE log under `log` directory.

Hope that helps.
