### ISSUE TITLE
Transparent Computing

### ISSUE THREAD

**Issue by lizitong67** [ashish-gehani/SPADE#99]
The latest SPADE requires CDM20, where could I find CDM20 dataset ？

**Comment by ashish-gehani** [comment]
AFAIK, they are not yet public.

**Comment by lizitong67** [comment]
> AFAIK, they are not yet public.

How do I use SPADE to store publicly available DARPA TC data（CDM18） in the Neo4j database？

**Comment by ashish-gehani** [comment]
SPADE's CDM Reporter can be used to ingest CDM data emitted by SPADE's CDM Storage. (It is not designed to handle data from other sources, which may use a different subset of the CDM schema.) See: https://github.com/ashish-gehani/SPADE/wiki/Ingesting-CDM

Since CDM evolved over the course of TC, the version supported depends on the Git tag, such as 'tc-e3' for Engagement 3. The data DARPA released in 2018 is from Engagement 3.

**Comment by UnnameBao** [comment]
I try to build spade with tc-e3 tag git version but I get an error:
> error: too many arguments to function ‘fd_sock->ops->getname'

How can I fix this?

**Comment by UnnameBao** [comment]
> SPADE's CDM Reporter can be used to ingest CDM data emitted by SPADE's CDM Storage. (It is not designed to handle data from other sources, which may use a different subset of the CDM schema.) See: https://github.com/ashish-gehani/SPADE/wiki/Ingesting-CDM
> 
> Since CDM evolved over the course of TC, the version supported depends on the Git tag, such as 'tc-e3' for Engagement 3. The data DARPA released in 2018 is from Engagement 3.

I try to build spade with tc-e3 tag git version but I get an error:
> error: too many arguments to function ‘fd_sock->ops->getname'

How can I fix this?

**Comment by ashish-gehani** [comment]
'tc-e3' runs on Ubuntu 14.04. This error indicates use of a Linux kernel >=4.17.
